x = int(input('Informe o número do mês'))
match x:
    case 1: print('Janeiro, primeiro trimestre')
    case 2: print('Feveiro, primeiro trimestre')
    case 3: print('Março,  primeiro trimestre')
    case 4: print('Abril,  segundo trimestre')
    case 5: print('Maio,  segundo trimestre')
    case 6: print('Junho,  segundo trimestre')
    case 7: print('Julho,  terceiro trimestre')
    case 8: print('Agosto,  terceiro trimestre')
    case 9: print('Setembro,  terceiro trimestre')
    case 10: print('Outubro, quarto trimestre')
    case 11: print('Novembro, quarto trimestre')
    case 12: print('Dezembro, quarto trimestre')
    case _: print('Mês inválido')
